site_name: pychain
theme:
  name: material

plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # IMPORTANT: résout tes imports sans bidouiller PYTHONPATH
          paths: ["src"]
          options:
            # ---- RENDU DES MEMBRES ----
            members_order: source          # respecte l’ordre dans tes fichiers
            inherited_members: true        # <- affiche les méthodes des mixins
            show_inheritance: true         # affiche "Bases: ..."

            # ---- RENDU DES SIGNATURES ----
            show_signature_annotations: true
            separate_signature: true       # signature sur sa propre ligne (moins “étiré”)
            line_length: 88                # wrap raisonnable

            # ---- RENDU DES DOCSTRINGS ----
            docstring_style: google        # (ou "numpy"/"sphinx" si tu préfères)
            show_if_no_docstring: true
            show_source: true              # lien "Source code in ..."
            show_overloads: true           # <-- rend les @overload

            # Si des bases venaient d’un package externe, décommente :
            # preload_modules:
            #   - some_external_pkg

nav:
  - Home: index.md
  - Reference:
      - Iter: reference/iter.md
      - Dict: reference/dict.md

# Live-reload quand tu modifies le code
watch:
  - src
theme:
  name: material
  palette:
    - scheme: slate         # dark
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default       # light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details
