site_name: pychain
theme:
  name: material

plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            members_order: source
            inherited_members: true
            show_inheritance: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 88
            docstring_style: google
            show_if_no_docstring: true
            show_source: true
            show_overloads: true 
nav:
  - Home: index.md
  - Reference:
      - Iter: reference/iter.md
      - Dict: reference/dict.md

theme:
  name: material
  palette:
    - scheme: slate         # dark
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default       # light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details
