[project]
name = "pychain"
version = "0.3.95"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cytoolz>=1.0.1",
    "numpy>=2.3.2",
]

[tool.ruff.format]
docstring-code-format = true


[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/OutSquareCapital/cytoolz-stubs.git" }

[dependency-groups]
dev = [
    "cytoolz-stubs",
]
[build-system]
requires = ["setuptools"]
