[build-system]
requires = ["setuptools>=61.0", "cython>=3.0.0", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pychain"
version = "0.3.95"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cytoolz>=1.0.1",
]

[tool.ruff.format]
docstring-code-format = true

[tool.setuptools.package-data]
"pychain" = ["py.typed"]

[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/OutSquareCapital/cytoolz-stubs.git" }

[dependency-groups]
dev = [
    "cytoolz-stubs",
]
