[project]
name = "pychain"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cytoolz>=1.0.1",
    "ipykernel>=6.29.5",
    "pandas>=2.3.1",
    "polars>=1.31.0",
    "pyfunctional>=1.5.0",
    "toolz>=1.0.0",
]

[tool.ruff.format]
docstring-code-format = true