[build-system]
requires = ["setuptools>=61.0", "cython>=3.0.0", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pychain"
version = "0.3.92"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.1.2",
    "ipykernel>=6.29.5",
    "setuptools>=80.9.0",
    "toolz>=1.0.0",
    "tqdm>=4.67.1",
    "appdirs>=1.4.4",
    "cytoolz>=1.0.1",
    "cytoolz-stubs",
]

[tool.ruff.format]
docstring-code-format = true

[tool.setuptools.package-data]
"pychain" = ["py.typed"]

[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/OutSquareCapital/cytoolz-stubs.git" }
