[project]
name = "pychain"
version = "0.3.99"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "cytoolz>=1.0.1",
    "more-itertools>=10.8.0",
    "rolling @ git+https://github.com/OutSquareCapital/rolling.git@add-type-stubs",
]
[dependency-groups]
dev = [
    "cytoolz-stubs",
    "numpy>=2.3.3",
    "pydoc-markdown>=4.8.2",
    "sphinx>=8.2.3",
    "sphinx-markdown-builder>=0.6.8",
]

[tool.ruff.format]
docstring-code-format = true

[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/py-stubs/cytoolz-stubs.git" }

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
