[build-system]
requires = ["setuptools>=61.0", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pychain"
version = "0.3.8"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.1.2",
    "cytoolz>=1.0.1",
    "ipykernel>=6.29.5",
    "pandas>=2.3.1",
    "polars>=1.31.0",
    "setuptools>=80.9.0",
    "toolz>=1.0.0",
    "numpy>=2.0",
    "tqdm>=4.67.1",
]

[tool.ruff.format]
docstring-code-format = true

[tool.setuptools.package-data]
"pychain" = ["py.typed"]
