[build-system]
requires = ["setuptools>=61.0", "cython>=3.0.0", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pychain"
version = "0.3.94"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "toolz>=1.0.0",
    "cytoolz>=1.0.1",
    "cytoolz-stubs",
    "polars>=1.32.3",
]

[tool.ruff.format]
docstring-code-format = true

[tool.setuptools.package-data]
"pychain" = ["py.typed"]

[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/py-stubs/cytoolz-stubs.git" }
