[project]
description     = "Method chaining for iterables and dictionaries in Python."
name            = "pyochain"
readme          = "README.md"
requires-python = ">=3.12"
version         = "0.5.2"

dependencies = ["cytoolz>=1.0.1", "more-itertools>=10.8.0", "rolling>=0.5.0"]

[dependency-groups]
dev = [
    "doctester",
    "griffe>=1.14.0",
    "mkdocs>=1.6.1",
    "mkdocs-autorefs>=1.4.3",
    "mkdocs-material>=9.6.22",
    "mkdocs-simple-hooks>=0.1.5",
    "mkdocstrings>=0.30.1",
    "mkdocstrings-python>=1.18.2",
    "polars>=1.33.1",
    "ruff>=0.14.1",
    "rolling @ git+https://github.com/OutSquareCapital/rolling.git@add-type-stubs",
    "cytoolz-stubs",
]

[tool.ruff.format]
docstring-code-format = true

[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/OutSquareCapital/cytoolz-stubs.git" }
doctester     = { git = "https://github.com/OutSquareCapital/doctester.git" }

[build-system]
build-backend = "uv_build"
requires      = ["uv_build>=0.8.15,<0.9.0"]
