[project]
name = "pychain"
version = "0.3.97"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cytoolz>=1.0.1",
    "more-itertools>=10.8.0",
    "numpy>=2.2.6",
    "rustats",
]

[tool.ruff.format]
docstring-code-format = true


[tool.uv.sources]
cytoolz-stubs = { git = "https://github.com/py-stubs/cytoolz-stubs.git" }
rustats = { git = "https://github.com/OutSquareCapital/rustats.git" }

[dependency-groups]
dev = [
    "cytoolz-stubs",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
