"""stubs for pychain - Chainable expressions for functional-style data processing."""

from collections.abc import Callable, Iterable
from random import Random
from typing import Any, Self

from ._protocols import CheckFunc, ProcessFunc, TransformFunc

expr: ExprConstructor
"""
Constructs chainable expressions for functional-style data processing.
"""
iter: IterConstructor
"""Constructs chainable iterators-focused functions for functional-style data processing.
"""
struct: StructConstructor
"""Constructs chainable dict-focused functions for functional-style data processing."""

class StructConstructor:
    def __call__[K, V](self, ktype: type[K], vtype: type[V]) -> Struct[K, V, K, V]: ...

class IterConstructor:
    def __call__[T](self, dtype: type[T]) -> Iter[T, T]: ...

class ExprConstructor:
    def __call__[T](self, dtype: type[T]) -> Expr[T, T]: ...

class BaseExpr[P, R]:
    def collect(self) -> Callable[[P], R]: ...
    def into_partial[T](
        self, f: Callable[[P], T], *args: Any, **kwargs: Any
    ) -> "Expr[P, T]": ...
    def compose(self, *fns: TransformFunc[R, R]) -> Self: ...

class Expr[P, R](BaseExpr[P, R]):
    def into[T](self, obj: Callable[[R], T]) -> "Expr[P, T]": ...

class Iter[V, V1](BaseExpr[Iterable[V], V1]):
    def agg[T](self, f: Callable[[Iterable[V]], T]) -> Expr[Iterable[V], T]: ...
    def into[T](self, obj: Callable[[Iterable[V]], T]) -> "Iter[V, T]": ...
    def group_by[K](self, on: TransformFunc[V, K]) -> dict[K, list[V]]: ...
    def into_frequencies(self) -> dict[V, int]: ...
    def reduce_by[K](
        self, key: TransformFunc[V, K], binop: Callable[[V, V], V]
    ) -> "Iter[V, K]": ...
    def map[T](self, f: TransformFunc[V, T]) -> "Iter[V, T]": ...
    def flat_map(self, f: TransformFunc[V, Iterable[V1]]) -> Self: ...
    def starmap(self, f: TransformFunc[V, V1]) -> Self: ...
    def compose(self, *fns: TransformFunc[V1, V1]) -> Self: ...
    def take_while(self, predicate: CheckFunc[V]) -> Self: ...
    def drop_while(self, predicate: CheckFunc[V]) -> Self: ...
    def interleave(self, *others: Iterable[V]) -> Self: ...
    def interpose(self, element: V) -> Self: ...
    def top_n(self, n: int, key: Callable[[V], Any] | None = None) -> Self: ...
    def random_sample(
        self, probability: float, state: Random | int | None = None
    ) -> Self: ...
    def concat(self, *others: Iterable[V]) -> Self: ...
    def filter(self, f: CheckFunc[V]) -> Self: ...
    def accumulate(self, f: Callable[[V, V], V]) -> Self: ...
    def insert_left(self, value: V) -> Self: ...
    def peek(self, note: str | None = None) -> Self: ...
    def peekn(self, n: int, note: str | None = None) -> Self: ...
    def head(self, n: int) -> Self: ...
    def tail(self, n: int) -> Self: ...
    def drop_first(self, n: int) -> Self: ...
    def every(self, index: int) -> Self: ...
    def repeat(self, n: int) -> Self: ...
    def unique(self) -> Self: ...
    def cumsum(self) -> Self: ...
    def cumprod(self) -> Self: ...
    def merge_sorted(
        self, others: Iterable[Iterable[V]], sort_on: Callable[[V], Any] | None = None
    ) -> Self: ...
    def tap(self, func: Callable[[V], None]) -> Self: ...
    def zip_with(
        self, others: Iterable[Iterable[V]], strict: bool = False
    ) -> "Iter[V, tuple[V, ...]]": ...
    def enumerate(self) -> "Iter[V, tuple[int, V]]": ...
    def flatten(self) -> "Iter[V, Any]": ...
    def diff(
        self,
        others: Iterable[Iterable[V]],
        default: Any | None = None,
        key: ProcessFunc[V] | None = None,
    ) -> "Iter[V, tuple[V, ...]]": ...
    def partition(self, n: int, pad: V | None = None) -> "Iter[V, tuple[V, ...]]": ...
    def partition_all(self, n: int) -> "Iter[V, tuple[V, ...]]": ...
    def rolling(self, length: int) -> "Iter[V, tuple[V, ...]]": ...
    def cross_join(self, other: Iterable[V1]) -> "Iter[V, tuple[V1, V]]": ...
    def first(self) -> Expr[Iterable[V], V1]: ...
    def second(self) -> Expr[Iterable[V], V1]: ...
    def last(self) -> Expr[Iterable[V], V1]: ...
    def length(self) -> Expr[Iterable[V], int]: ...

class Struct[K, V, K1, V1](BaseExpr[dict[K, V], dict[K1, V1]]):
    def collect(self) -> Callable[[dict[K, V]], dict[K1, V1]]: ...
    def map_keys[T](self, f: TransformFunc[K, T]) -> "Struct[K, V, T, V1]": ...
    def map_values[T](self, f: TransformFunc[V, T]) -> "Struct[K, V1, K1, T]": ...
    def select(self, predicate: CheckFunc[K]) -> Self: ...
    def filter(self, predicate: CheckFunc[V]) -> Self: ...
    def filter_on_key(self, key: K, predicate: CheckFunc[V]) -> Self: ...
    def with_key(self, key: K, value: V) -> Self: ...
    def with_nested_key(self, keys: Iterable[K] | K, value: V) -> Self: ...
    def update_in(self, *keys: K, f: ProcessFunc[V]) -> Self: ...
    def merge(self, *others: dict[K, V]) -> Self: ...
    def merge_with(
        self, f: Callable[[Iterable[V]], V], *others: dict[K, V]
    ) -> Self: ...
    def drop(self, *keys: K) -> Self: ...
    def flatten_keys(self) -> "Struct[K, V, str, V1]": ...
