name: Deploy Documentation

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Setup Python
        run: uv python install 3.13
      
      - name: Install dependencies
        run: uv sync --group dev
      
      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force