name: Publish Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # Indispensable pour l'authentification OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyochain
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      
      - name: Setup Python
        run: uv python install 3.13
      
      - name: Build package
        run: uv build
      
      - name: Publish package to PyPI
        run: uv publish